function [] = pronto_gui

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% to use type pronto_gui like so:  EDU >> pronto_gui
% 
% PRONTO_GUI needs PRONTO_GOODS.m to work 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

subplot(2,2,1)
% make function call here set(gca,'Tag','Plot1');
title('Plot One goes here')
axis([0 pi 0 1.2]);

subplot(2,2,2)
%set(gca,'Tag','Plot2');
title('Plot two can go here or so . . .');

subplot(2,2,4)
%set(gca,'Tag','Plot3');
title('Another Jazzy Plot goes here');


background = get(gcf,'Color');

s1 = uicontrol('Style', 'slider',...
   'Units','normalized',...
   'Visible', 'on',...
   'Min', 0,...
   'Max', pi,...
   'Value',0,...
   'Position',[0.13 0.41 .2 .06],...
   'Tag','Slider1',...
   'Callback','lsqfilt_update(''Slider'')',...
   'SliderStep',[0 0.2]);
s2 = uicontrol('Style', 'slider',...
   'Units','normalized',...
   'Min', 0,...
   'Max', pi,...
   'Value',pi/2,...
   'Position',[0.13 0.31 .2 .06],...
   'Tag','Slider2',...
   'Callback','lsqfilt_update(''Slider'')',...
   'SliderStep',[0 0.2]);
s3 = uicontrol('Style', 'slider',...
   'Units','normalized',...
   'Min', 0,...
   'Max', pi,...
   'Value',pi/100,...
   'Position',[0.13 0.21 .2 .06],...
   'Tag','Slider3',...
   'Callback','lsqfilt_update(''Slider'')',...
   'SliderStep',[0 0.1]);
s4 = uicontrol('Style', 'slider',...
   'Units','normalized',...
   'Min', 3,...
   'Max', 100,...
   'Value',3,...
   'Position',[0.13 0.11 .2 .06],...
   'Tag', 'Slider4',...
   'Callback','lsqfilt_update(''Slider'')',...
   'SliderStep',[0 .2]);

t1 = uicontrol('Style','text',...
   'Units','normalized',...
   'String','Omega 0',...
   'Position',[0.03 0.39 0.1 0.06],...
   'BackgroundColor',background,...
   'HorizontalAlignment','center');
t2 = uicontrol('Style','text',...
   'Units','normalized',...
   'String','Omega 1',...
   'Position',[0.03 0.29 0.1 0.06],...
   'BackgroundColor',background,...
   'HorizontalAlignment','center');
t3 = uicontrol('Style','text',...
   'Units','normalized',...
   'String','Delta',...
   'Position',[0.03 0.19 0.1 0.06],...
   'BackgroundColor',background,...
   'HorizontalAlignment','center');
t4 = uicontrol('Style','text',...
   'Units','normalized',...
   'String','Taps',...
   'Position',[0.03 0.09 0.1 0.06],...
   'BackgroundColor',background,...
   'HorizontalAlignment','center');

e1 = uicontrol('Style','edit',...
   'Units','normalized',...
   'Position',[0.35 0.41 0.08 0.06],...
   'BackgroundColor',background,...
   'String','0',...
   'Tag','Edit1',...
   'Callback','lsqfilt_update(''Edit'')');
e2 = uicontrol('Style','edit',...
   'Units','normalized',...
   'Position',[0.35 0.31 0.08 0.06],...
   'BackgroundColor',background,...
   'String','1.5',...
   'Tag','Edit2',...
   'Callback','lsqfilt_update(''Edit'')');
e3 = uicontrol('Style','edit',...
   'Units','normalized',...
   'Position',[0.35 0.21 0.08 0.06],...
   'BackgroundColor',background,...
   'String','0',...
   'Tag','Edit3',...
   'Callback','lsqfilt_update(''Edit'')');
e4 = uicontrol('Style','edit',...
   'Units','normalized',...
   'Position',[0.35 0.11 0.08 0.06],...
   'BackgroundColor',background,...
   'String','3',...
   'Tag','Edit4',...
   'Callback','lsqfilt_update(''Edit'')');

m1 = uicontrol('Style','popupmenu',...
   'Units','normalized',...
   'String',{'Least Squares','Hamming'},...
   'Position',[0.18,0.03,0.2,.05],...
   'BackgroundColor',background,...
   'Tag','FilterMenu',...
   'Callback','lsqfilt_update(''Filter'')');


% Display the default filter before the user changes
% any parameters.

lsqfilt_update('Slider');
